<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--<GenerateDocumentationFile>True</GenerateDocumentationFile>-->
    <OutputPath>..\lib</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <VVVVInstallPath>C:\Program Files\vvvv\vvvv_gamma_8.0-0170-g6f2eb6d984-win-x64</VVVVInstallPath>
    <RepoRootPath>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..'))</RepoRootPath>
    <VVVVRepoPath>$([System.IO.Path]::GetFullPath('$(RepoRootPath)'))</VVVVRepoPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="VL.Core" Version="2026.8.0-0170-g6f2eb6d984" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="VL.Core" />
    <Using Include="VL.Core.Import" />
    <Using Include="VL.Lib.Collections" />
    <Using Include="Stride.Core.Mathematics" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\OrbbecSDK_DotNet\src\*.cs">
      <LinkBase>sdk</LinkBase>
    </Compile>
  </ItemGroup>

</Project>
